### PR TITLE
fix: issues #56, #64, #81, #85 & #88

### PR DESCRIPTION
**Pull request by DennisPitallano**
#56
Added DCRDEX & Komodo Wallet DEX 
- this only applies to English transactions

image

#64
Removed Digi-Broker & DigiAsset Tools 

- remove https://createdigiassets.com and https://digi-broker.com/index.php/tools/ from the "See DigiAssets in action" section
image

#81
Update forward thinking 
- update the first sentence by dynamically adding year diff.
applied to all languages
image

#85
Removed Crypto Bantam 
- remove Crypto Bantam https://www.cryptobantam.com/vendor/dgbat/ links

#88
fix Outdated Site © Copyright 
 - created an appendCopyrightDate() function to append the copyright year to the footer with dynamic current year value
- applied to all languages

image

### CODE REVIEW

**Comment by Sbosvk** [comment]
Will await more input before reviewing this.
Thank you again @DennisPitallano for doing this, unfortunately it was necessary to lift the topic whether we actually want #62.

**Review by Sbosvk — CHANGES_REQUESTED** [review]
Please remove commit 44a23a42e56b7ccdb8ca03db874823de286e11a9 from this PR for now so that we can move forward.

**Comment by DennisPitallano** [comment]
> Please remove commit [44a23a4](https://github.com/DigiByte-Core/DGBio/commit/44a23a42e56b7ccdb8ca03db874823de286e11a9) from this PR for now so that we can move forward.

reverted commit 44a23a42e56b7ccdb8ca03db874823de286e11a9
see commit  c380ed56720e03d44447a3d1f240a68e6d606b59

**Comment by Sbosvk** [comment]
This is a bit strange...I can clearly see the commit to revert the info paper change, but when checking that change out and testing, and looking at code, `#socialmedia` is still there. I think we need to use `git cherry-pick` here as there seems to be a conflict with commit 44a23a42e56b7ccdb8ca03db874823de286e11a9 and c380ed56720e03d44447a3d1f240a68e6d606b59.

**Comment by Sbosvk** [comment]
Ignore my last comment (that I deleted but that you have gotten over email)...Haven't had enough sleep and mixed things up..My apologies.

**Review by Sbosvk — APPROVED** [review]
Thank you again for this, @DennisPitallano, great work! Also thank you for reverting that commit.

**tACK**.

**Review by ycagel — APPROVED** [review]
cACK. Thank you @DennisPitallano!

**Pull request merged**
