### PR TITLE
2023/q3

### PR DESCRIPTION
**Pull request by Sbosvk**

### CODE REVIEW

**Review by ycagel — APPROVED** [review]
cACK. Thank you Oliver!

**Review by fgabelmannjr — CHANGES_REQUESTED** [review]
@Sbosvk , thank you for this contribution.  It is very appreciated.

Could you please separate the commenting of the mobile app div into a separate PR please?  I don't have much time this week but I would like to build this locally to confirm what happens when it is commented out.  I am also curious if the intent here is to replace it with a different image.  Either way, I would prefer to see this code removed or modified rather than commented out.

**Review by gto90 — CHANGES_REQUESTED** [review]
@Sbosvk , thank you for this contribution. It is very appreciated.

Could you please separate the commenting of the mobile app div into a separate PR please? I don't have much time this week but I would like to build this locally to confirm what happens when it is commented out. I am also curious if the intent here is to replace it with a different image. Either way, I would prefer to see this code removed or modified rather than commented out.

**Comment by Sbosvk** [comment]
The intent is indeed to replace the hero image once a good replacement has been found, so I have left it commented out to easily just make use of the hero functionality without having to search through documentation for the feature. 

I have tested these changes, it leaves an empty space for sure but it does not break anything. I can split up the commits but I would prefer if this could just simply be tested and reviewed as is. If we have some sort of contribution guideline for this repo that I have missed please point me to it so I can align accordingly.

**Comment by gto90** [comment]
> The intent is indeed to replace the hero image once a good replacement has been found, so I have left it commented out to easily just make use of the hero functionality without having to search through documentation for the feature.
> 
> I have tested these changes, it leaves an empty space for sure but it does not break anything. I can split up the commits but I would prefer if this could just simply be tested and reviewed as is. If we have some sort of contribution guideline for this repo that I have missed please point me to it so I can align accordingly.

We do not have any official contribution guidelines on this repo like we do the protocol.  However, it makes it easier to review PRs when they are atomic and focused on one discreet change at a time.

With respect to the commented-out code, I would also like to test to see what the result is but won't have time to do so for a few days.  That said if you can submit the CNAME and donation link changes as separate PRs I believe we can get at least those approved and merged.

**Comment by Sbosvk** [comment]
Since what you are asking me to split is in the same commit essentially you are asking me to re-do this work all over again instead of just testing it out, it is not something I can cherry-pick. Honestly this is not a very reasonable request for the reasons given. I don't see why you can not simply checkout the branch, serve it, and just open it in a browser.

Furthermore, the DigiByte Mobile app is dead, it is dead, why are we not prioritizing removing references to it and especially so on the top of the front page? Is it not more important right this moment to have it removed rather than caring about commented out code that will be repurposed?

If I have to wait for a few more days to get this merged then fine. This is not my website, this is our website, it shouldn't have to be about me wanting to apply changes as soon as possible it should be about all of us wanting to.

**Comment by Sbosvk** [comment]
Screenshot from 2023-09-23 09-48-21
Screenshot from 2023-09-23 09-47-40

**Review by gto90 — APPROVED** [review]
ACK

**Pull request merged**
