### PR TITLE
RTL design improvement for Video section

### PR DESCRIPTION
**Pull request by Daniel-Leedan**
## Before:
video-before

## After:
video-after

### CODE REVIEW

**Comment by makyurt** [comment]
Thank you for your contribution. It is merged now. But kept the play button position as floated left because it blocks DigiByte logo on mobile view.

IMG_1FB86E9CB11D-1

**Comment by Daniel-Leedan** [comment]
Good catch! Do you think we can keep the button position floated right just on desktop? 
It feels more natural for RTL languages speakers.

```
.rtl .btn-video {
    right: 9%;
    left: auto;
}
```

```
@media only screen and (max-width: 1200px) {
   .rtl .btn-video {
       left: 9%;
       right: auto;
   }
}
```

**Comment by makyurt** [comment]
Good idea. I did it as "max-with: 1000px". Also changed button height percentage for the resolutions under 1000px for better view.

**Comment by Daniel-Leedan** [comment]
Great, Thanks!

I found a few more minor things to improve the RTL, I will PR soon as possible.

**Pull request merged**
